### PR TITLE
test change

### PR DESCRIPTION
**Pull request by villelaitila**

### CODE REVIEW

**Comment by villelaitila** [comment]
screen shot 2017-07-17 at 20 50 03

Here is the visualization: /tmp/graphvisualizer/_softagram_output_projects_a6c49f6e-b748-4039-8397-99124198c891_fea6_2017-07-18_15-05-51Z_dependency_modelfile.xml.zip_impact.png

**Comment by JoeNguyen93** [comment]
Test comment for pull request

**Comment by JoeNguyen93** [comment]
Test comment for pull request

**Comment by JoeNguyen93** [comment]
Test comment 3 for pull request

**Comment by villelaitila** [comment]
Impact Graph

 High impact!

**Comment by villelaitila** [comment]
Impact Graph

 High impact!

**Comment by villelaitila** [comment]
Impact Graph

 High impact!

**Pull request merged**
